Sigmund
expertanalytics/rasputin pull request #36
Opened 2020-03-05 08:22 UTC by sigmunsl

Added texture support

2020-03-05 08:57 UTC, skavhaug requested changes
Some minor comments, plus one serious regarding scale and texture image size.

2020-03-05 08:57 UTC, skavhaug commented on src/rasputin/geometry.py
> +        self.scale_y = 1
We should really do this part more properly

2020-03-05 08:57 UTC, skavhaug commented on web/index.html
> +        <script type="module" src="index.js"></script>
Should we follow our prev pattern and include the resource?

2020-03-05 08:57 UTC, skavhaug commented on web/index.js
> +import {GUI} from 'https://threejsfundamentals.org/threejs/../3rdparty/dat.gui.module.js';
Perhaps wait with the gui part to a different PR?

2020-03-05 08:57 UTC, skavhaug commented on web/index.js
> +
Delete these lines

2020-03-05 08:57 UTC, skavhaug commented on web/index.js
> +
Remove these lines

2020-03-05 08:57 UTC, skavhaug commented on web/index.js
> +    return new THREE.Mesh(geom, geomMaterial);
We don't need this function anymore?

2020-03-06 12:58 UTC, sigmunsl commented on web/index.js
> +    return new THREE.Mesh(geom, geomMaterial);
Fixed

2020-03-06 12:58 UTC, sigmunsl commented on web/index.js
> +
Fixed

2020-03-06 12:58 UTC, sigmunsl commented on web/index.js
> +
Fixed

2020-03-06 13:12 UTC, skavhaug approved these changes
LGTM!

2020-03-06 13:13 UTC, skavhaug commented
We should really get some automatic testing in place for rasputin soon. We should make this our next effort!

2020-03-06 13:58 UTC, merged